### ISSUE TITLE
une semaine de 7 semaines

### ISSUE THREAD

**Issue by newick** [oncletom/detour.studio#5]
> Petite semaine, que j'ai commencée en prenant 2 semaines de repos.

2 jours j'imagine ;)

**Comment by thom4parisot** [comment]
Hé bien, c'est pas clair mais j'ai vraiment décidé de commencer la semaine en m'accordant 2 semaines de repos !

Je vais clarifier qu'il s'agit d'une décision :-)

Merci de m'avoir pointé du doigt ce bout de texte !

**Comment by newick** [comment]
aaaah oooh ! J'ai peut-être besoin de repos aussi ^^
